In [1]:
%load_ext autoreload
%autoreload all

In [2]:
from phreeqcrm import YAMLPhreeqcRM

In [3]:
from phreeqpy.phreeqcrm.rm_model import PhreeqcRMModel

In [4]:
model = PhreeqcRMModel('ex11-advect.yaml')

In [5]:
model

PhreeqcRMModel('ex11-advect.yaml')

In [6]:
model.rm_variables['DensityUser']

RMVariable((BMIPhreeqcRM(), 'DensityUser'))

In [7]:
model.update()

In [8]:
model.rm_variables['DensityUser']

RMVariable((BMIPhreeqcRM(), 'DensityUser'))

In [9]:
model.component_names

('H', 'O', 'Charge', 'Ca', 'Cl', 'K', 'N', 'Na')

In [10]:
model.rm_variables

RMVariables(BMIPhreeqcRM())

In [11]:
model.concentrations

In [36]:
[name for name in dir(model._rm) if 'yaml' in name.lower()]

['GetGridCellCountYAML', 'InitializeYAML']

In [37]:
model._rm.InitializeYAML?

Signature: model._rm.InitializeYAML(yamlfile)
Docstring:
A YAML file can be used to initialize an instance of PhreeqcRM.

Args:
        YAML_file: String containing the YAML file name.

Returns:
        IRM_RESULT: 0 is success, negative is failure (See
                :meth:`DecodeError`).

The file contains a YAML sequence of PhreeqcRM methods
and the arguments corresponding to the methods.

For example,

- key: LoadDatabase
  database: phreeqc.dat
- key: RunFile
  workers: true
  initial_phreeqc: true
  utility: true
  chemistry_name: advect.pqi

:meth:`InitializeYAML` will read the YAML file and execute
the specified methods with the specified arguments. Using
YAML terminology, the argument(s) for a method may be a
scalar, a sequence, or a map, depending if the argument is
a single item, a single array, or there are multiple
arguments. In the case of a map, the names associated with
each argument (for example 'chemistry_name' above) is
arbitrary. The names of the map keys for map arguments are
not used in parsing the YAML file; only the order of the
arguments is important.

The class YAMLPhreeqcRM can be used to write a YAML file.
The methods defined in the YAMLPhreeqcRM class include the
following list; all but SetGridCellCount and ThreadCount
correspond to PhreeqcRM methods.

CloseFiles(void);
CreateMapping(float list, numpy.ndarray, or tuple: grid2chem);
DumpModule();
FindComponents();
InitialEquilibriumPhases2Module(int list, numpy.ndarray, or tuple: ic);
InitialExchanges2Module(int list, numpy.ndarray, or tuple: ic);
InitialGasPhases2Module(int list, numpy.ndarray, or tuple: ic);
InitialKinetics2Module(int list, numpy.ndarray, or tuple: ic);
InitialPhreeqc2Module(int list, numpy.ndarray, or tuple: initial_conditions1);
InitialPhreeqc2Module_mix(int list, numpy.ndarray, or tuple: initial_conditions1,
        int list, numpy.ndarray, or tuple: initial_conditions2,
        float list, numpy.ndarray, or tuple: fraction1);
InitialPhreeqcCell2Module(int n,
        int list, numpy.ndarray, or tuple: cell_numbers);
InitialSolidSolutions2Module(int list, numpy.ndarray, or tuple: ic);
InitialSolutions2Module(int list, numpy.ndarray, or tuple: ic);
InitialSurfaces2Module(int list, numpy.ndarray, or tuple: ic);
LoadDatabase(string database);
OpenFiles(void);
OutputMessage(string str);
RunCells(void);
RunFile(Boolean workers,
        Boolean initial_phreeqc,
        Boolean utility,
        string chemistry_name);
RunString(Boolean workers,
        Boolean initial_phreeqc,
        Boolean utility,
        string input_string);
ScreenMessage(string str);
SetComponentH2O(Boolean tf);
SetConcentrations(float list, numpy.ndarray, or tuple: c);
SetCurrentSelectedOutputUserNumber(int n_user);
SetDensityUser(float list, numpy.ndarray, or tuple: density);
SetDumpFileName(string dump_name);
SetErrorHandlerMode(int mode);
SetErrorOn(Boolean tf);
SetFilePrefix(string prefix);
SetGasCompMoles(float list, numpy.ndarray, or tuple: gas_moles);
SetGasPhaseVolume(float list, numpy.ndarray, or tuple: gas_volume);
SetGridCellCount(int nxyz);
SetPartitionUZSolids(Boolean tf);
SetPorosity(float list, numpy.ndarray, or tuple: por);
SetPressure(float list, numpy.ndarray, or tuple: p);
SetPrintChemistryMask(int list, numpy.ndarray, or tuple: cell_mask);
SetPrintChemistryOn(Boolean workers,
        Boolean initial_phreeqc,
        Boolean utility);
SetRebalanceByCell(Boolean tf);
SetRebalanceFraction(float f);
SetRepresentativeVolume(float list, numpy.ndarray, or tuple: rv);
SetSaturationUser(float list, numpy.ndarray, or tuple: sat);
SetScreenOn(Boolean tf);
SetSelectedOutputOn(Boolean tf);
SetSpeciesSaveOn(Boolean save_on);
SetTemperature(float list, numpy.ndarray, or tuple: t);
SetTime(float time);
SetTimeConversion(float conv_factor);
SetTimeStep(float time_step);
SetUnitsExchange(int option);
SetUnitsGasPhase(int option);
SetUnitsKinetics(int option);
SetUnitsPPassemblage(int option);
SetUnitsSolution(int option);
SetUnitsSSassemblage(int option);
SetUnitsSurface(int option);
SpeciesConcentrations2Module(float list, numpy.ndarray, or tuple: species_conc);
StateSave(int istate);
StateApply(int istate);
StateDelete(int istate);
UseSolutionDensityVolume(Boolean tf);
WarningMessage(string warnstr);

Returns:
        IRM_RESULT: 0 is success, negative is failure (See :meth:`DecodeError`).
File:      ~/Dev/phreeqpy_project/phreeqpy/.pixi/envs/default/lib/python3.14/site-packages/phreeqcrm/phreeqcrm.py
Type:      method

In [45]:
YAMLPhreeqcRM.YAMLThreadCount?

Signature: YAMLPhreeqcRM.YAMLThreadCount(self, nthreads)
Docstring:
Inserts data into the YAML document for the method ThreadCount.

When the YAML document is written to file it can be processed by the method InitializeYAML to
initialize a PhreeqcRM instance.ThreadCount provides the number of threads to use in
OpenMP multiprocessing when used to initialize a BMIPhreeqcRM instance, provided the
BMIPhreeqcRM instance was created with the default constructor--the constructor with
no arguments.
File:      ~/Dev/phreeqpy_project/phreeqpy/.pixi/envs/default/lib/python3.14/site-packages/phreeqcrm/yamlphreeqcrm.py
Type:      function

In [9]:
gfw = model.rm_variables['Gfw']

In [10]:
gfw._

AttributeError: 'RMVariable' object has no attribute '_'

In [23]:
model.molalities

         N     Na           H   Cl   Ca       K          O
0   0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
1   0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
2   0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
3   0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
4   0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
5   0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
6   0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
7   0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
8   0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
9   0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
10  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
11  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
12  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
13  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
14  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
15  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
16  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
17  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
18  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
19  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
20  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
21  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
22  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
23  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
24  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
25  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
26  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
27  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
28  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
29  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
30  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
31  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
32  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
33  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
34  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
35  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
36  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
37  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
38  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352
39  0.0012  0.001  111.012434  0.0  0.0  0.0002  55.510352

In [21]:
model.concentrations

In [46]:
yrm = YAMLPhreeqcRM()

In [50]:
yrm.YAMLInitialPhreeqc2Module_mix?

Signature: yrm.YAMLInitialPhreeqc2Module_mix(ic1, ic2, f1)
Docstring:
Inserts data into the YAML document for the PhreeqcRM method InitialPhreeqc2Module with three arguments.

When the YAML document is written to file it can be processed by the method InitializeYAML to
initialize a PhreeqcRM instance. InitialPhreeqc2Module transfers solutions and reactants from the
InitialPhreeqc instance to the reaction-module workers, possibly with mixing.
In its simplest form, initial_conditions1 is used to select initial conditions,
including solutions and reactants, for each cell of the model, without mixing.
Initial_conditions1 is dimensioned 7 times nxyz, where nxyz is the number of grid cells
in the user's model. The dimension of 7 refers to solutions and reactants in the following
order: (0) SOLUTIONS, (1) EQUILIBRIUM_PHASES, (2) EXCHANGE, (3) SURFACE, (4) GAS_PHASE,
(5) SOLID_SOLUTIONS, and (6) KINETICS.The definition initial_solution1[3*nxyz + 99] = 2,
indicates that cell 99 (0 based) contains the SURFACE definition (index 3) defined by
SURFACE 2 in the InitialPhreeqc instance (either by RunFile or RunString).

It is also possible to mix solutions and reactants to obtain the initial conditions for cells.
For mixing, initials_conditions2 contains numbers for a second entity that mixes with the
entity defined in initial_conditions1. Fraction1 contains the mixing fraction for
initial_conditions1, whereas (1 - fraction1) is the mixing fraction for initial_conditions2.
The definitions initial_conditions1[3*nxyz + 99] = 2, initial_conditions2[3*nxyz + 99] = 3,
fraction1[3*nxyz + 99] = 0.25 indicates that cell 99 (0 based) contains a mixture of
0.25 SURFACE 2 and 0.75 SURFACE 3, where the surface compositions have been defined in the
InitialPhreeqc instance. If the user number in initial_conditions2 is negative, no mixing occurs.
@param initial_conditions1 A list, tuple, or numpy array of solution and reactant index numbers that refer to
definitions in the InitialPhreeqc instance.
@param initial_conditions2  A list, tuple, or numpy array of solution and reactant index numbers that refer to
definitions in the InitialPhreeqc instance. Nonnegative values of @a initial_conditions2
result in mixing with the entities defined in @a initial_conditions1. Negative values result
in no mixing.
@param fraction1 A list, tuple, or numpy array of fraction of initial_conditions1 that mixes with (1 - fraction1)
of initial_conditions2.
File:      ~/Dev/phreeqpy_project/phreeqpy/.pixi/envs/default/lib/python3.14/site-packages/phreeqcrm/yamlphreeqcrm.py
Type:      method

In [53]:
yrm.YAMLSetConcentrations?

Signature: yrm.YAMLSetConcentrations(c)
Docstring:
Inserts data into the YAML document for the PhreeqcRM method SetConcentrations.

When the YAML document is written to file it can be processed by the method InitializeYAML to
initialize a PhreeqcRM instance. The only way to use this method is to have pre-calculated
PHREEQC solution concentrations, which is not common. Concentrations are normally initialized
with YAMLInitialPhreeqc2Module, YAMLInitialPhreeqcCell2Module, or the methods
YAMLInitialSolutions2Module, YAMLInitialEquilibriumPhases2Module, and other similar methods
for other reactants.
@param c A list, tuple, or numpy array of component concentrations. Size of vector is ncomps times nxyz,
where ncomps is the number of components as determined by FindComponents or GetComponentCount and
nxyz is the number of grid cells in the user's model.
File:      ~/Dev/phreeqpy_project/phreeqpy/.pixi/envs/default/lib/python3.14/site-packages/phreeqcrm/yamlphreeqcrm.py
Type:      method

In [52]:
dir(yrm)

['Clear',
 'GetList',
 'WriteYAMLDoc',
 'YAMLAddOutputVars',
 'YAMLCloseFiles',
 'YAMLCreateMapping',
 'YAMLDumpModule',
 'YAMLFindComponents',
 'YAMLInitialEquilibriumPhases2Module',
 'YAMLInitialExchanges2Module',
 'YAMLInitialGasPhases2Module',
 'YAMLInitialKinetics2Module',
 'YAMLInitialPhreeqc2Module',
 'YAMLInitialPhreeqc2Module_mix',
 'YAMLInitialPhreeqcCell2Module',
 'YAMLInitialSolidSolutions2Module',
 'YAMLInitialSolutions2Module',
 'YAMLInitialSurfaces2Module',
 'YAMLLoadDatabase',
 'YAMLLogMessage',
 'YAMLOpenFiles',
 'YAMLOutputMessage',
 'YAMLRunCells',
 'YAMLRunFile',
 'YAMLRunString',
 'YAMLScreenMessage',
 'YAMLSetComponentH2O',
 'YAMLSetConcentrations',
 'YAMLSetCurrentSelectedOutputUserNumber',
 'YAMLSetDensityUser',
 'YAMLSetDumpFileName',
 'YAMLSetErrorHandlerMode',
 'YAMLSetErrorOn',
 'YAMLSetFilePrefix',
 'YAMLSetGasCompMoles',
 'YAMLSetGasPhaseVolume',
 'YAMLSetGridCellCount',
 'YAMLSetNthSelectedOutput',
 'YAMLSetPartitionUZSolids',
 'YAMLSetPorosity',
 'YAMLSetPressure',
 'YAMLSetPrintChemistryMask',
 'YAMLSetPrintChemistryOn',
 'YAMLSetRebalanceByCell',
 'YAMLSetRebalanceFraction',
 'YAMLSetRepresentativeVolume',
 'YAMLSetSaturationUser',
 'YAMLSetScreenOn',
 'YAMLSetSelectedOutputOn',
 'YAMLSetSpeciesSaveOn',
 'YAMLSetTemperature',
 'YAMLSetTime',
 'YAMLSetTimeConversion',
 'YAMLSetTimeStep',
 'YAMLSetUnitsExchange',
 'YAMLSetUnitsGasPhase',
 'YAMLSetUnitsKinetics',
 'YAMLSetUnitsPPassemblage',
 'YAMLSetUnitsSSassemblage',
 'YAMLSetUnitsSolution',
 'YAMLSetUnitsSurface',
 'YAMLSpeciesConcentrations2Module',
 'YAMLStateApply',
 'YAMLStateDelete',
 'YAMLStateSave',
 'YAMLThreadCount',
 'YAMLUseSolutionDensityVolume',
 'YAMLWarningMessage',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'yaml_doc']